### ISSUE TITLE
Can't pause my scenes (Overlay Scenes) (2.8)

### ISSUE THREAD

**Issue by adorno-dev** [UPBGE/upbge#1100]
Unfortunately overlay scenes features are disabled due to eevee, I can't see a way to pause my game project without them.
Is there any alternative solution to resolve this problem?
I just want to pause a scene and be able to resume it again without change my scene.

PS: My English is a work in progress.. Thx.

**Comment by youle31** [comment]
For now, instead of suspend scene, you can suspend some scene objects physics and logic.

For physics, there is an actuator (edit object > dynamics > suspend physics (it can work for children of an empty)
For logic, you can run objects logic only when the HUD is not enabled (either with python and a boolean property, either with properties sensors/actuators). This is less handy than with overlay scenes but i see only that for now.

Maybe later, we could replace suspend scene with an actuator suspend collection which would suspend physics AND/OR logic for an entire collection.

This branch is still very experimental and a WIP

**Comment by adorno-dev** [comment]
> For physics, there is an actuator (edit object > dynamic

Man.. I really appreciate your suggestion.
you gave me a solution that works for while.
I'm gonna put it inside a component to all pausable objects.
Thank you so much.
