### ISSUE TITLE
Game crash on Start with Collection Instance

### ISSUE THREAD

**Issue by IzaZed** [UPBGE/upbge#1108]
I didn't find an Issue where this is mentioned, so here goes:

When I add an instance of a Collection, the game crashes on startup.
Maybe I'm doing something wrong, but this seems like a major issue to me.

Could this be similar to #1104 maybe?

**Comment by RomStef** [comment]
maybe you can share an example file

**Comment by youle31** [comment]
Yes, we would need a simple test file please. But basically bge for now does a very basic use of collections, and no instanced collections should be used.

**Comment by youle31** [comment]
I don't know instanced collections but in this file it doesn't crash for me:

http://pasteall.org/blend/index.php?id=52855

**Comment by IzaZed** [comment]
Sorry for not providing a file
Basically just take your file and uncheck the instanced collection (Collection 1) in the outliner

Apparently in the Game Engine it can't reference that collection anymore, which means you would have to have the original collection active somwhere in the game

I'ts possible to hide the collection, but not deactivate it - it's probably not urgent after all, I forgot one can just hide things

**Comment by youle31** [comment]
Actually, in all the bge code in 2.8, collections are just used at BlenderDataConversion 1 time to say if the objects are in an active layer or an inactive layer. If the eye is white, the object is considered to be in an active layer. If the eye is grey, the object is considered to be in an inactive layer. This is the only usage of collections in bge code. Then only the eye matter.

For example if you want to add an object, the eye of the object (and maybe of the object's coolection too) must be greyed. This is the only use we have of collections in the code.

I have no idea about what can be the impact of other outliner options in bge, this is why I think it is better to not use it (because in bge code, only the eye matters, and if you combine the eye with other things, the depsgraph can be lost and maybe it can cause a crash... idk). But I never worked on that.

**Comment by youle31** [comment]
Fixed in https://github.com/UPBGE/upbge/commit/44f4409ed2420f09dac59bd4086e86f662fd92f3
