### ISSUE TITLE
Accecssing the bpy.data  Slow down the FPS

### ISSUE THREAD

**Issue by RomStef** [UPBGE/upbge#1114]
I Have noticed that accecssing the bpy.data  Slow down the FPS

**Comment by youle31** [comment]
normally, if you use modules, you don't necessarly need to access bpy.data each frame, idk if it would solve the issue

**Comment by RomStef** [comment]
the texture coords of the clouds need to be update each frame if i want to move them in realtime, this is the reason why have asked the restore of the timer in the shader node editor. I can use a simple animation as workaround i think. i don't know if the noise texture is to heavy for this purpose

**Comment by youle31** [comment]
Noise procedural texture is to avoid absolutely because of big performances impact, in all nodes setups. procedural textures should be avoided as long as it is possible because it requires extra computations. But some procedural textures has less cost than others. Simple benchmarcks with simple test files can be done to evaluate the impact of each procedural texture.

**Comment by RomStef** [comment]
Understood , thanks again.
