### ISSUE TITLE
Glitches in rendering when camera is moving.

### ISSUE THREAD

**Issue by sanath111** [UPBGE/upbge#1151]
I'm using the daily build of upbge-eevee, I have a player mesh and camera parented to it. so when i press "P" and start moving the player, the material on character seems distorted. This problem does not appear when camera is not moving.

![animation_glitch](https://user-images.githubusercontent.com/39722154/77061503-5497cc00-6a00-11ea-8b6d-3f1419c9133b.gif)

**Comment by youle31** [comment]
I think this is caused by viewport denoising.

You can try to disable it in render tab > sampling.

Then you can add the fxaa glsl filter:
- In text editor > templates > openGL shading langage, click on fxaa.glsl to open the filter in the text editor.
- On the main camera, add an always sensor (without pulse mode), add a custom 2D filter actuator and select fxaa.glsl. Link sensor and actuaor.

Start game to see if it improves the rendering.

Note: Disabling viewport denoising can impact other eevee's post processing effects (AO for example), then if you disable viewport denoising, some eevee's post processing effects won't work properly.

**Comment by sanath111** [comment]
Thank you very much. It worked.
