### ISSUE TITLE
performance regressions

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/upbge#1157]
somewhere after the 13th the animation system now costs 10x more and logic cost appears to be doubled.

what was costing .3 -> .4 ms is costing  3 - 4 ms

https://www.youtube.com/watch?v=O-X_VjHm_BQ

I can make my game available to debug with - test

**Comment by youle31** [comment]
We can do nothing with that. Please follow the bug report guide: https://github.com/UPBGE/upbge/wiki/Report-a-bug-guide

**Comment by youle31** [comment]
And it would be nice to prepare the job because fixing a bug like that takes hours if we need to bisect/revert commits/find the bottleneck in a complex file, then we need the file, as simplified as possible, the exact build version since when it is not working anymore as lordloki makes many builds and it's not that hard to download and test

**Comment by BluePrintRandom** [comment]
I tried all loki's builds and the regression is not there
trying my own build fresh from today to see if maybe it's my env

**Comment by BluePrintRandom** [comment]
it's my env - after 14 was depreciated  - something about swapping to 15 has my env borked - starting from scratch

**Comment by BluePrintRandom** [comment]
clean build env - no problem
