### ISSUE TITLE
 My UPBGE 0.2.4 closes alone

### ISSUE THREAD

**Issue by elyakimklettke** [UPBGE/upbge#1173]
if i create a new scene in the upbge 0,2,4 downloading in official website   and try to put some material in some object, or in creating a new environment data the program closes alone.

![2](https://user-images.githubusercontent.com/35348168/79026657-eb6b2a80-7b5f-11ea-8be4-718f55a1d2ca.png)
![3](https://user-images.githubusercontent.com/35348168/79026665-ee661b00-7b5f-11ea-94a7-cbd61db2755a.png)
![4](https://user-images.githubusercontent.com/35348168/79026670-ef974800-7b5f-11ea-9c30-d64e87dc68ad.png)

**Comment by elyakimklettke** [comment]
my system information
[informações do sistema.txt](https://github.com/UPBGE/upbge/files/4463591/informacoes.do.sistema.txt)

**Comment by youle31** [comment]
This bug reminds me somthing which was related to ColorManagement.
It was fixed by Blender developers in last upbge versions based on last blender2.7 master.

Can you try ge_23a_old_bullet downloadable here:

https://github.com/UPBGE/upbge/issues/1041

last builds from youle based on last blender2.7 master

**Comment by youle31** [comment]
As there is no further feedback, I close this task.
