### ISSUE TITLE
UPBGE crashes when Decrease X (width) Resolution

### ISSUE THREAD

**Issue by Shohrukh1999** [UPBGE/upbge#1195]
Hi, ***UPBGE developers!***
When I increase the resolution of the width (X), everything *works fine*, also with increasing and decreasing the height (Y), but when I want to reduce the resolution of the width (X), **UPBGE crashes.**
This error can be seen only in **Standalone Start.**
P.S. I am using UPBGE 0.3 Alpha.
Date: 2020-04-17 02:09
Hash: "834126c1e15b" 
And again, maybe I made a mistake somewhere.
[Decrease X Resolution BUG.zip](https://github.com/UPBGE/upbge/files/4537042/Decrease.X.Resolution.BUG.zip)

**Comment by lordloki** [comment]
Hi,
It crashes because you have a bug in your logic code
![image](https://user-images.githubusercontent.com/1015605/80333637-02dc3000-884f-11ea-90ec-68527f72e1ec.png)
Then when you want to decrease the width, really you are assinging to X the -1 value and it crashes because the value can't be a negative value (it has to be higher than zero).
I close the report. Thanks for reporting.

**Comment by Shohrukh1999** [comment]
Oops, my bad!

**Comment by lordloki** [comment]
No problem :-)
