### ISSUE TITLE
Enable/Disable Shadow High Bitdepth = Strange Effect

### ISSUE THREAD

**Issue by Shohrukh1999** [UPBGE/upbge#1196]
# Hi, *UPBGE developers!*
When I click on the plane that toggles Shadow High Bitdepth **(in the upper left corner),** the switch seems to work as it should if you *look at Debug Properties.*
But when you ***press once and wait a bit,*** the scene *slowly darkens.*
There is a cube in the scene that can be moved using WASD. When you move the cube everything again becomes as it was before clicking.
If you click again, then we repeat the cycle.
P.S. If, again, somewhere is my mistake, then forgive me for my carelessness.
[ARGH.zip](https://github.com/UPBGE/upbge/files/4546050/ARGH.zip)
EDIT 1: Use Standalone Start.
EDIT 2: I'm using UPBGE 0.3 Alpha.
Date: 2020-04-17 02:09
Hash: "834126c1e15b"

**Comment by youle31** [comment]
You can have such weird effects when everything is static on the scene. This is because when nothing moves, TAA samples are incremented by 1 each frame. In most cases, this gives a very good image quality, but in some cases it can cause this can of behaviour.

We are aware of these problems but for now, we didn't choosed if we give the possibility to disable TAA or to limit the amount of samples (which can cause weird pixel movement), or if we try to investigate on DRW_state_is_image_render.

If you want to avoid the image to be more and more dark, you can execute a python script each frame doing: bge.logic.getCurrentScene().resetTaaSamples = True

We'll choose later about potential changes to do about taa behaviour. Also, maybe RAS_FrameBuffer creation can maybe take into account this option (highbit depth)...

**Comment by BluePrintRandom** [comment]
![image](https://user-images.githubusercontent.com/7190873/80538634-ec22ff80-895a-11ea-90fd-990558693863.png)

I wonder if we are using TAA optimizations for static geometry ?

http://twvideo01.ubm-us.net/o1/vault/gdc2016/Presentations/Pedersen_LasseJonFuglsang_TemporalReprojectionAntiAliasing.pdf

**Comment by youle31** [comment]
I close this because i'm bored that someone tries to show me papers.
