### ISSUE TITLE
Render.py

### ISSUE THREAD

**Issue by Shohrukh1999** [UPBGE/upbge#1198]
# Hi, *UPBGE developers!*
I want to share a script that has most of the EEVEE settings and some UPBGE settings.
In some places in the code, I could not use lists (they are immediately noticeable, these sections of code contain several elif-s). (Note that I'm not a professional coder, I'm just learning coding).
You can put this code in Text Editor-> Templates.
I hope someone needs this script.
[Render.zip](https://github.com/UPBGE/upbge/files/4547342/Render.zip)
@lordloki, can you take a look at this script?
EDIT: You can make comments on how to improve this script. So I will not only fix and improve the code, but also get invaluable coding experience for me.

**Comment by youle31** [comment]
I'm sorry, but I don't think ask a developer to review your script is the role of the bug tracker.
We have already too much of things to do and each time someone adds a request or report a bug here, this can stress us whereas we only work for free. This can be answered by other people than upbge contributors elsewhere. Then I close this task. If lordloki wants to answer, he can because he had the mail...

**Comment by BluePrintRandom** [comment]
maybe post your code to a git and then do a pull ?
