### ISSUE TITLE
UPBGE 0.3 Alpha Crashes a lot and randomly;

### ISSUE THREAD

**Issue by MakataUrugami** [UPBGE/upbge#1217]
That isn't new. Even with old Blender BGE it still happens, I don't know why.

I do believe that in most of cases it occurs when I'm typing script. Sometimes it takes a while to occur, but I literally don't know what I'm doing wrong to make it crash.

Windows 10 - 64 bit.

**Comment by youle31** [comment]
Hi, without more informations, we can do nothing.
If it is crashing while you're not at bge runtime, there are chances that the bug comes from blender code (as we are a fork of blender and we only work on bge part).

You can eventually open blender from a console and try to reproduce the crash, then give us the console log, but even just with a console log, it might be difficult to identify the problem.

As this report has not needed infos for us to identify the problem, I close this report but if you have more infos (console logs, examples files, exact steps to reproduce the bug...), feel free to open a new bug report.
