### ISSUE TITLE
Blender v0.3 Alpha Navmesh and Steering doesn't work.

### ISSUE THREAD

**Issue by MakataUrugami** [UPBGE/upbge#1224]
I create a fresh and empty file, create two cubes that is enemy and target. Next I create a big cube right in the middle to be the obstacle and a plane as the floor.
Select both the plane and big cube and bake navmesh, everything still fine.
I put a always sensor connected to the steering actuator, select the target and the navmesh objects, clicked on navmesh and "reset index values", physics of the enemy as dynamic.

Press "p", and the enemy go straigh to hit the wall... I laugh.

The blender scene:
[Mechanic Test.zip](https://github.com/UPBGE/upbge/files/4767513/Mechanic.Test.zip)

I know that is a alpha and later on should be fixed but I feel more comfortable saying.

Any help are welcome, y'all are the best.

My system:
Windows 10 - 64 bit;
GTX770;
AMD FX 8320;

**Comment by lordloki** [comment]
Choose Path finding instead of seek in the actuator do the trick.
Anyway, navmesh is only recovered in a basic way and reseting index, rebuild, etc is very susceptible to crash. No navmesh color yet. 
The technical reason is because navmesh has no ID and it should. We will improve it (not yet but we will).

**Comment by MakataUrugami** [comment]
Thank you, it did solve my problem!
