### ISSUE TITLE
Python component fails to recognize some BGE type names (e.g. KX_Camera)

### ISSUE THREAD

**Issue by mysticfall** [UPBGE/upbge#1240]
When I create a simple Python module and add a reference to some of the builtin types like `bge.types.KX_Camera`, it fails to register with an error saying that it cannot find the given type under `types`.

It can be reproduced with the following source:
```python
import bge


class SimpleComponent(bge.types.KX_PythonComponent):

    camera: bge.types.KX_Camera

    def __init__(self, base_object):
        pass

    def start():
        pass

    def update():
        pass
```

**Comment by lordloki** [comment]
I need to recover all pyhton components commit first. I will recovery them this week and test this issue after

**Comment by youle31** [comment]
I think this would suppose to fake all bge types as it was done for bge.types.KX_PythonComponent. This seems not really doable.
The code should be in start or update method I think because only called at bge runtime after all bge types have been initialized.

**Comment by youle31** [comment]
you can define all your classes inherited from bge.types.KX_Camera or something else in another file and import these classes in start() method.

**Comment by mysticfall** [comment]
I'm afraid the suggested workaround wouldn't be a viable option for me since my intention is to use type-hints for my APIs whenever possible.

Sorry if I'm talking about something entirely silly, as my knowledge of the internals of UPBGE is near non-existent at the moment.

It's my vague understanding that the module `bge` exists during the play and that's why it throws an error if I just type `import bge` in the Blender console.

If that is to be the case, would it be possible to temporarily "play" the project while registering a component?

And I've talked with the author of `fake-bpy-module` about the possibility of extending the project to add support for UPBGE and he/she was very enthusiastic about it. So, if we could have such an auto-generated stubs for the whole BGE API, would it change anything regarding this issue, like temporarily using it to resolve references while registering a component?

I know I'm just throwing out things at random, but I'm quite desperate to have this problem solved, moving from Scala/Java/C# background.

**Comment by youle31** [comment]
You can look at how it is faked in python_comonent.c (I don't understand much too). You can compare to what is done in KX_PythonInit. Maybe there would be a trick but... idk. Components are done in a way where you have to put your runtime code in start and update methods which are called during runtime.

**Comment by mysticfall** [comment]
@youle31 Thanks for the info. I'll look into the part you mentioned as I'm even willing to learn C/C++/Python just to solve these issues. I'm that desperate about it :)

**Comment by youle31** [comment]
Python Components are very special. The idea was to give the possibility to experienced coders to create and share kindof custom logic bricks, but it needs to follow the existing scheme to define the class with the start and update method called at runtime after bge module has been initialized.

Maybe you would be more comfortable with logic bricks + python controller which is the normal way to do python in bge since ages... But here too, the code is called during bge runtime (after the bge module and the bge types have been initialized)

**Comment by mysticfall** [comment]
I'm still learning UPBGE, but is it possible to assign properties to a Python controller via UPBGE's editor U like I can with a component?

And I thought `KX_PythonComponent` was an equivalent of Unity's `MonoBehaviour`, which provides a way to implement a game object's behavior in a compositional manner. Does python controller play a similar role as components in this aspect as well?

**Comment by youle31** [comment]
You have either an UI for game properties or you can create game properties in python.

With logic bricks, there's almost nothing visual if you only use an always sensor + a python controller.

The python controller is accessible like that:

import bge

cont = bge.logic.getCurrentController()
own = cont.owner #the object which has the python controller on it.

You can create a game property like that:

own["myProperty"] = 1.0

if "myProperty" is already the name of a game property created with the UI you can access it directly:

myVariable = own["myProperty"]

You can also access the current scene (KX_Scene):

scene = bge.logic.getCurrentScene()

And you can also access all scene objects (KX_GameObject):

objList = scene.objects

You can access a KX_GameObject in scene.objects like that:

cube = scene.objects["Cube"] #the bge.types.KX_GameObject named Cube

KX_GameObjects are the structures used to represent the gameobjects in bge module during runtime, but in upbge0.3, each KX_GameObject has a corresponding bpy.types.Object:

blenderCube = cube.blenderObject

You can access the mesh (with all vertices... like that):

blenderCubeMesh = blenderCube.data #the Mesh if Object type is an OB_MESH

You can perform most of operations available in the viewport during runtime because you can use both bge and bpy (bpy is the module used for each operation in the viewport).

There would be thousands of things to say, but i can't here....

**Comment by mysticfall** [comment]
@youle31 // Thanks for the guide. It's good to know that I can access properties from a Python controller. I agree that it's a good thing to have such a way to easily glue game logics and game objects together.

Without any intention to argue what could be the best way to write game code, I'll just say that I normally end up with hundreds of classes, inheriting each other, in whatever project that I do with a language that supports OOP.

I understand that it's not something usual, or even recommended to do in simple game projects, but it's a major part of the reason why I'm interested in starting a game project. I want to use it as a testbed for trying out various design approach that I have in mind.

So, it's just a requirement for me when evaluating a game engine to use for my project, to have comparable expressiveness and freedom in design choices as I would have if I work on a non-game project.

**Comment by youle31** [comment]
Even if upbge has some strength (like the workflow -> all in one program), it remains something done by hobbyists. When bge was removed from Blender, we tried to adapt it to have it working with blender 2.8, but we are hobbyists, I don't think the game engine could be used for a serious/big project. We are only 2 to maintain it as a hobby, there can be possible performances issues in some situations, we can't answer complex requests. The code design itself is weird because because in blender 2.7 bge was almost "independant" from blender code. Today with upbge0.3, we need to keep some old parts of the code separate from blender (physics), but the render is done directly with eevee. It results in a weird design where you need to use 2 python modules (bge + bpy) to do a game.

Then it's up to you to see if you can/want to use it for your project...

**Comment by mysticfall** [comment]
Don't worry, I'm just a hobbyist myself :smile: Even though my project is likely to be a complex one (as I will do my own share of weird stuffs with it) I don't have any definite timeline nor desire it to become a commercial project.

If something doesn't work, I can wait until UPBGE 14.3 solves the issue (that is, if I can survive until then), so I'm mostly fine with the problem.

Thanks for the warning, though!

**Comment by mysticfall** [comment]
I have some beginner questions about how UPBGE works, by the way:

What is the main reason that `bge` module cannot be initialized with the other modules when Blender starts?

Would it be viable if we can temporarily initialize `bge` module during the registration process (i.e. `logic_ops.component_register_exec`) and dispose it?

Provided we have `fake-bge-module` which provides stubs for BGE APIs, would it be a viable approach to install it by default, then replace it with the real module during the game play (i.e. `KX_PythonInit.initGamePlayerPythonScripting`) and restore it when it's finished?

**Comment by youle31** [comment]
- I can't answer why bge module is not initialized at blender start. I just know/see that gameengine was designed to be independant from blender. Then the module is initialized when the game engine is launched and freed when the game engine exits, I guess. I never asked myself the question before.

- Maybe it would be possible but i'm too noob to really know. It would need to call the code in KX_PythonInit and KX_PythonInitypes I guess.

- I don't know how blender developers manage the python version bundled with blender. I know that some python modules bundled with the normal python like "tkinter" are not in the blender python. This would need to modify blender python library sources though I guess, and I don't really know if it would be a viable approach, but what could be done is to try to understand how autocompletion for bpy module works in python interactive console in blender.

**Comment by youle31** [comment]
I close this thread as with the current design of python components, it is "normal" that bge types are not recognized outside of bge runtime because the bge module and bge types are not initialized.

**Comment by mysticfall** [comment]
I'd like to argue that it'd be better if we can keep this issue open, even though it is unlikely that we will find a suitable solution soon.

Now I understand that the problem is caused by a fundamental design choice that BGE took, but that doesn't mean that it is not a limitation for its users or that it's impossible to solve.

I'm still new to Python, but it's my understanding that the need for type hints is quite strong among many of its developers which can be seen from the popularity of such a tool as `mypy`, or the fact that the language itself started to provide such a mechanism since a recent version.

This issue means that you have to abandon any sort of type hints for core BGE APIs when they are referenced from `KX_PythonComponent`, which I see to be a significant limitation. It feels even so, since now we have a working `fake-bge-module` so that we can use any Python IDE to enjoy autocompletion and type checking of BGE APIs, _if_ we don't use them in `KX_PythonComponent`.

I have to admit that we don't have too many people in the community who think this to be a blocking concern, and also that it's not my current priority to investigate into potential solutions for this problem.

But hopefully, we may become more popular in future and attract more Python programmers to try UPBGE. Then, I believe I won't be the last person to see this issue to be a major limitation of the engine, and maybe we can even find someone who has better knowledge of C++/Python than me to propose a working solution to the problem.

It's just my personal opinion, so I'd respect it if you decide to keep this issue closed. But when it's pretty much the norm in most of the big projects to have at least a few long standing issues in their backlogs, I don't think we should ignore such a significant limitation to keep the issue list clean.

**Comment by mysticfall** [comment]
Thanks much! :smile_cat:

**Comment by youle31** [comment]
I reopened the issue. But I just want to say that I don't consider myself bge based on 2.8 as a viable long term good project. It inherits from old contestables design choices that interactive mode (the future blender "game engine") should solve. Only bpy module should be used... And a more complete integration with blender... But as I told to the blender foundation chairman (Ton Rosendaal), I'm not experienced enough to start such a project from scratch, and this is why when blender foundation removed bge, I tried to do my best to keep it and adapt it to blender 2.8.

But considering big design remaining issues that I wouldn't be abled to solve, and even if I like to tinker with upbge in 2.8, it's very strange from coding point of view... (years ago, I called this project "game engine transition", like something just to do a transition between old bge and future interactive mode....).

But of course anyone can try to improve/do something with existing code : )

**Comment by mysticfall** [comment]
I understand that for a project as old as UPBGE (including its former existence as 'BGE'), there may exist fundamental design limitations which would make a complete overhaul or even reimplementation to be more suitable than incremental attempts to refactor the codebase.

I'd welcome the change if there comes a time when we'd have a better, official alternative to BGE in future. I just want to enjoy  a bit of autocompletion and static type checking until we get there. And it will also make the transition easier for me, if I can refactor my codebase with confidence, as my IDE will detect most of the errors I may make if my codebase is well annotated with type hints.

On a side note, I still fancy `fake-bge-module` may be exploited to workaround the problem, as we only need to provide stubs for BGE APIs (not the actual ones) while the user provided module source is loaded to make this work. I may visit this issue after I'm done with what I'm currently working on and give it a serious try.

>  I'm not experienced enough to start such a project from scratch, and this is why when blender foundation removed bge, I tried to do my best to keep it and adapt it to blender 2.8.

From what I've seen so far, you've been doing a fantastic job and I appreciate it! :)
