### ISSUE TITLE
Related to the Logic Node Add-On: prop_search causes crash when file contains linked NodeTrees

### ISSUE THREAD

**Issue by IzaZed** [UPBGE/upbge#1277]
I encountered a problem with the Node Add-On in 0.3.0

The more recent Builds seem to have a problem with linked NodeTrees, causing Blender to quit as soon as a prop_search for NodeTrees is triggered.
The Nodes that cause this issue are the ones in the "Logic Tree" Category of the AddOn. It happens as soon as a new Tree is linked, be it a material group or a logic tree

Any idea on what could cause this? I'm out of ideas.

**Comment by lordloki** [comment]
Could you post an small imagen or blend to try or reproduce it?

I did some tests but i'm not very good with logic nodes and i couldn't crash
![image](https://user-images.githubusercontent.com/1015605/91640823-918cd380-ea20-11ea-91e8-8b522cadfc1e.png)

**Comment by IzaZed** [comment]
It shouldn't need a particular node setup

Posting a blend is difficult because you need a linked NodeTree from another file to get it to crash

- Basically, link any NodeTree from a different file (Shader Groups or Logic Trees are NodeTree datablocks) with Ctrl+Shift+O
- Create a New Logic Tree
- Add a Node from the Logic Tree Category
- Try to select a NodeTree

That should lead to the crash

**Comment by youle31** [comment]
Hi, I guess this problem is related to a blender commit related to nodetrees more than something related to bge's code?
What you can do is trying to find between which versions of upbge 0.3 the crash begun to appear (in old builds). Then look at the git log between the 2 dates to see if there is a commit from jackques Luckes or any other blender developer related to nodetrees which could be the cause of the crash.

Also, you can check here: https://developer.blender.org/maniphest/ if a similar bug has not been reported?

**Comment by lordloki** [comment]
It is a blender commit between 28-06-2020 (works) and 05-07-2020 (not work)

**Comment by lordloki** [comment]
The issue is the problematic commit that added 3 extra characters. I'm investigating how to solve it

**Comment by youle31** [comment]
Ah! Cool! Thanks lordloki!

**Comment by IzaZed** [comment]
It's working, I can load up my files again 👍 Generated Code from linked Trees is also working as far as I can tell

Closing this, Thanks lordloki!
