### ISSUE TITLE
OpenColorIO Error:Error could not read 0.3

### ISSUE THREAD

**Issue by srhighwizard** [UPBGE/upbge#1342]
hello, I created a game in 0.3 and published it for sale, I know it's still in alpha, but one person reported this error when trying to open the game:
"OpenColorIO Error: Error could not read"
does anyone have any idea what it could be, and if there is how to solve it?

**Comment by lordloki** [comment]
From which date exactly?
Do you export your game with the game export addon?
It seems that it didn't find the config.ocio file.
Could you check if this file is under colormanagement directory in 2.9X?

**Comment by srhighwizard** [comment]
yes, i used the standard tool to export. the error happened yesterday, with a specific person from asia who acquired the game.
I noticed that some files are missing in the "datafiles" folder
compared to blender itself, is that the problem?

**Comment by lordloki** [comment]
The issue comes from OpenColorIO and it is inherited by Blender itself and by us.
See that: https://developer.blender.org/T82081 and https://github.com/AcademySoftwareFoundation/OpenColorIO/issues/406

The solution is to put the game in a folder without non-ascii (chinese, japanese, etc) characters.

**Comment by srhighwizard** [comment]
it worked! thank you!
