### ISSUE TITLE
Rigid Body Constraints Generic 6 Dof super bug

### ISSUE THREAD

**Issue by mushroomeo** [UPBGE/upbge#1392]
hi i played whole day trying to setup character with rigid body joint constraint with Pivot type: Generic 6 DoF. but only realized how super bugged it is, because it all time jiggeling and dont want stop.. the limits for angle just doesnt work

here the test file and video 

[Generic 6 DoF madness.zip](https://github.com/UPBGE/upbge/files/5921024/Generic.6.DoF.madness.zip)

please lets change constraints...

**Comment by lordloki** [comment]
It sound a lot to me. I already investigate this same issue 7 years ago :-) https://developer.blender.org/T42115

It is a limitation of this bullet 6DOF constraint (due to use euler instead of quaternions). Basically, the Y-axis only allows +/-90 degrees as maximum of rotation to avoid that the constrain goes haywire. In your case you can modify your model to avoid that the rotation matches with the Y local axis of your object.

[Testing spawning collection_modified.zip](https://github.com/UPBGE/upbge/files/5921599/Testing.spawning.collection_modified.zip)

This time I will put a note in the manual :-)
