### ISSUE TITLE
3D sound cuts out on left side of Camera

### ISSUE THREAD

**Issue by Maltreated1** [UPBGE/upbge#1433]
Created a basic scene consisting of basic FPS logic brick setup.
Cube attached to rotating object on Z axis, running a walking sound loop on the cube via logic bricks with 3d sound enabled.
Added another cube on the left side of the scene with a looping humming sound.
Sound cuts out on the left channel, even when standing right next to a sound source.
Using Upbge 0.30.0 Alpha build from 12 March.

**Comment by lordloki** [comment]
Hi, we need a test file to check. It can be a lot things (sound stereo, etc)

**Comment by Maltreated1** [comment]
Thanks lordloki.

Link to test file. Sound files should be packed into the blend.
https://drive.google.com/file/d/1sSB55JBCyR9lSKzJ6RdDpGgsiqExgNbs/view?usp=sharing

**Comment by lordloki** [comment]
There is 2 issues:
- The footstep are stereo. If you convert to mono it works better.
- The cube has not the origin in the geometry. The sound is projected from geometry's origin due to this the footstep sound always in camera position although the cube is far away.
![image](https://user-images.githubusercontent.com/1015605/111036676-b4ad2c80-8420-11eb-9318-d653db284b0b.png)

![image](https://user-images.githubusercontent.com/1015605/111036698-d3132800-8420-11eb-9a29-ced6f7c04966.png)

**Comment by Maltreated1** [comment]
Thank you lordloki for taking the time to look at the file.
I totally forgot about mono for 3D spatial audio.
I didn't notice the origin location.
Turns out the fault wasn't with Upbge, but completely a fault of my own.
My headphone jack wasn't completely inserted and has slipped from the port.
Sorry for wasting your time, many thanks.

**Comment by lordloki** [comment]
No problem, thanks for reporting. Closing the issue.
