### ISSUE TITLE
Animation of custom Property not executable in logic brick editor

### ISSUE THREAD

**Issue by BerglerAndi** [UPBGE/upbge#1445]
Hey there,
 i have a problem with playing animations of custom properties in the logicbrick actuator. I use the custom properties to control materials. The first object with i made works. But all further objects with animated custom properies i made, don't work. In my example the light with red an green work perfect. But the white light doesn't do.

btw: if i copy the first object, it will work..

![grafik](https://user-images.githubusercontent.com/58920393/112540531-95b08200-8db2-11eb-82e5-d7d0110578ea.png)
[CustomProp_Animation.zip](https://github.com/UPBGE/upbge/files/6207735/CustomProp_Animation.zip)

**Comment by BluePrintRandom** [comment]
personally I would use object color and py or actions with the object color

this is already allocated per object I believe.

**Comment by youle31** [comment]
Actually, i tag it as a bug because it shouldn't be working at all. Idk why for now, the modifier on the cylinder makes it playable.
The BL_Action code needs to be changed i guess...

About animating materials with drivers, it is more a feature request than a bug then a discussion could be opened but wouldn't treated with same priority than the bug.
