### ISSUE TITLE
UPBGE 0.3 Object Text don't work in overlay collection mode.

### ISSUE THREAD

**Issue by fumangy** [UPBGE/upbge#1481]
I have tested last version and I have this issue in console , when I make  an accountant with object Text  (Error: failed convert font property "Text").
Attach video and blend file. 
Thanks ,  best regards.
Toni.
UPBGE   2021-05-15 
[Contador.blend.zip](https://github.com/UPBGE/upbge/files/6490224/Contador.blend.zip)
 

https://user-images.githubusercontent.com/29063438/118415658-f0c46e00-b6ab-11eb-8ca9-c05fe33c31df.mov

**Comment by fumangy** [comment]
It seems that for it to work, there has to be some moving object, rotation, or having some kind of physics, rigid body, dynamic, character and this moving.
If the scene is completely static it does not work.
This is correct.
Thank you.
[Contador_1.mov.zip](https://github.com/UPBGE/upbge/files/6493241/Contador_1.mov.zip)
[Contador_1.blend.zip](https://github.com/UPBGE/upbge/files/6493243/Contador_1.blend.zip)

**Comment by lordloki** [comment]
It seems that it is necessary to add a notify for viewport update in overlay

**Comment by youle31** [comment]
Yes, it's because when the logic is updated, a notifier is added but this notifier is flushed during first render pass, and not anymore in overlay pass... This bug can concern all places where notifiers are added during logic pass (BL_Action...). Objects notified/tagged 1 time during logic could be flushed again, or maybe only at last render pass.

**Comment by lordloki** [comment]
The last build hasn't got the issue. Thanks to youle for the fix. Closing the report. Thanks for the feedback.

**Comment by fumangy** [comment]
Thanks devs for made this amazing engine in to blender.
