### ISSUE TITLE
soft bodys behave weirdly

### ISSUE THREAD

**Issue by mushroomeo** [UPBGE/upbge#1486]
if you add soft bodys in game then they are instanced which is unusable...

**Comment by youle31** [comment]
Yes, I think it's because of rasmesh->GetOriginalObject...

**Comment by youle31** [comment]
Actually for both issues (materials + softbodies), I think the easier solution would be to to use convertBlenderObject. For now, there is only python for this. We could eventually add an UI to load a duplicated object from another .blend. I'll close material issue because it's basically the same issue.

**Comment by youle31** [comment]
Fixed here: https://github.com/UPBGE/upbge/commit/f407e98057a4dd2cc302663bea3dfd6d9639a9ca

Thanks for report
