### ISSUE TITLE
Bullet serialization missing triangle mesh collision shape

### ISSUE THREAD

**Issue by VitorMouro** [UPBGE/upbge#1517]
When trying to export a .bullet file using `bge.constraints.exportBulletFile(filename)` the objects with collision bounds of type triangle mesh aren't serialized.

Version: 0.30.0 alpha

**Comment by lordloki** [comment]
It seems as you can see here: https://pybullet.org/Bullet/phpBB3/viewtopic.php?t=6217 that the issue is that UPBGE/Blender is using btScaledBvhTriangleMeshShape internally for "instances" of the mesh and that class isn't serialized yet.
Then the issue is in Bullet library itself. You will have to add a new issue in bullet github.
