### ISSUE TITLE
Reminder: LOD issues

### ISSUE THREAD

**Issue by IzaZed** [UPBGE/upbge#1519]
It seems that the LOD system stops working when using one file to get to another
Like using an empty laucher to jump into another file

The example has 2 files, just open the launcher and press P, that will load into the other file where there should be a cube (the main object's LOD), but instead it shows the original object - that can be checked by simply opening LODtest.blend, it shows the cube there
[LOD.zip](https://github.com/UPBGE/upbge/files/6862567/LOD.zip)

**Comment by youle31** [comment]
As discussed on discord, it was because camera lodfactor was set to 0.0. There can be remaining issues with LOD so i leave the issue opened. like:
- lodfactor is not taken into account in viewport (should we take it into account?)
- problem with hidden lodlevels at ge runtime (no evaluated mesh for lod with modifier)

**Comment by IzaZed** [comment]
The issue for me was that I was importing objects at runtime and converting them to GameObjects before assigning the LODs, changing that order fixed the problem for me, so the original reason for this issue was actually my fault

We can leave this open nonetheless if you want

**Comment by youle31** [comment]
Thanks for update. Yeah, ok. I'll close as I fixed the main issue I saw here: https://github.com/UPBGE/upbge/commit/e3765c60dcfa11f460fa19e2be614c26452417be

About lodfactor working in viewport, it's not very important and we can see later.
