### ISSUE TITLE
0.2.5.b startSound() with 3D sounds doesn't working correctly

### ISSUE THREAD

**Issue by JeffRayner** [UPBGE/upbge#1520]
I was testing a project with a sound actuator, and I noticed that when starting the 3D sound, the execution doesn't work correctly.
When moving the camera from away the object that is emitting the sound, the volume isn't changed either.

The error only happens using the Python component.

Using logic bricks works correctly.

[testSound3D.zip](https://github.com/UPBGE/upbge/files/6871670/testSound3D.zip)

**Comment by AC-Panda** [comment]
# Information

Logic-Bricks are automatically put to sleep when not connected to one another.
Python Components cannot properly activate an actuator that is asleep.
In my example demo, I demonstrate that all you need to do is connect some extra bricks to the actuator.
**NOTE:** This will play the sound at least once due to the sensor being an always sensor, but you **can fix** this issue by making it a property sensor or other such statement driven sensor.

# Screenshot

![UPBGE_0 2x_Python_Components_Activate_Actuator](https://user-images.githubusercontent.com/69180012/127561264-114299b0-e39d-4861-b503-f97e35e5e2ff.png)

# Blend
[testSound3D_mine.zip](https://github.com/UPBGE/upbge/files/6903420/testSound3D_mine.zip)
