### ISSUE TITLE
I have two issue

### ISSUE THREAD

**Issue by donjwan88** [UPBGE/upbge#1576]
first :
the collision didn't work fine , it works once properly and again it doesn't work

second : 
variables don't work properly
I don't know where the problem please check this file

https://www.youtube.com/watch?v=QBRyWKOy5ls

[untitled5.zip](https://github.com/UPBGE/upbge/files/7372761/untitled5.zip)

**Comment by IzaZed** [comment]
The collision problem can be fixed by setting the physics substep (in the scene panel) to something above 3
In recent UPBGE builds the physics calculation has been a bit strange for me too, but since it's just using the external Bullet engine that's likely an issue over there

About the variables, what's not working there? I didn't find any variable nodes in your trees

**Comment by IzaZed** [comment]
Ah I see
There's a few issues here
 - The Key Released node should be set to "Once" (this will be renamed to "Tap")
 - You're only refilling the tank when it's still above 0, so once it's gone, it's gone for good
 - The way you work with animations is rather chaotic, you can split the whole animation of the player into scaling and UV-Panning
 
[untitled5.zip](https://github.com/UPBGE/upbge/files/7392839/untitled5.zip)

 Here's a modified file, though I have to admit that I don't know if it's gonna work for you since it was build with the current architecture rework branch - but the node setup itself should give you an idea of what I mean :)
