### ISSUE TITLE
Can’t select objects in the viewport but blender works fine. (macos, intel)

### ISSUE THREAD

**Issue by nurb2kea** [UPBGE/upbge#1595]
Can’t select objects in the viewport macos. If I try blender 3.0 or 3.1 selecting things works fine - anyone else have that issue?
I get the same issue when I compile blender myself, but compiled by blender.org works always fine.!

Hope someone got a solution , information or hint on that.

Thanks in advance

PS: macOS 12.0.1 intel, latest xcode and updates...

**Comment by lordloki** [comment]
Hi, this is not due to any bug in Blender or UPBGE itself. This is due to compile the code with Xcode 13 because the compiler has a bug. The investigation is here: https://developer.blender.org/T91680

@TriVoxel are you using XCode 13. In https://developer.blender.org/T91680 there is a possible patch (which decress the perfomance) or the other solution is to use a XCode < 13. Maybe I can generate the build for intel side but I have to learn how to do the signature and notarization.

**Comment by nurb2kea** [comment]
Big thank you very much for the help and hints. I was close to become stupid with this bug.
I thought after xcode update to 13.1 that now it will work, then I thought it must be something else...etc...

Good to know that they are on it. Because porting back to xcode 12.5.1 isn't the best idea in terms of the actual macOS.

**Comment by lordloki** [comment]
Could test the build I just uploaded?
https://github.com/UPBGE/upbge/releases/download/v0.30/UPBGE-0.30-macOS-x86_64.dmg
It is compiled with a xcode < 13

**Comment by nurb2kea** [comment]
Looks like brecht is fixing it via blender 3.0.1 woraround...
https://developer.blender.org/T93479
https://developer.blender.org/T91680

**Comment by lordloki** [comment]
Yeah, I saw it. In fact, that bugfix is already included in current upbge 0.31 alpha but it would be interesting if you can test the build above to confirm if this upbge 0.3 build fix the issue. Thanks in advance.

**Comment by nurb2kea** [comment]
I you compiled it and it's working, then everything is fine.
What do you need me to install your version.

If I would down the source & compile it on my machine, then it would make sense.

**Comment by lordloki** [comment]
Ok, I confirm that it is working in the build I uploaded.
Thanks for the report and the feedback. Closing the issue.
