### ISSUE TITLE
Game Property name and type show as null!

### ISSUE THREAD

**Issue by rollalt** [UPBGE/upbge#1604]
If you put the info screen and create a property , changing name and type will show as bpy.data.objects["name"].(null) ="""

Is giving error when running script that set type name for properties.

**Comment by lordloki** [comment]
Hi, 
we need a small blend showing the issue as I don't understand fully what you are trying to say me. Thanks

**Comment by rollalt** [comment]
Lordloki sport but the last 4 rows are with the issue. 

.(null) is the issue

**Comment by lordloki** [comment]
Ahh, that is a known issue that occurs in other parts of Blender too.

To create a property from scripting
For example, you have a 'Cube' and you add a bool property called HIDE:
bpy.ops.object.game_property_new(type='BOOL', name="HIDE")
bpy.data.objects['Cube'].game.properties['HIDE'].value=True
bpy.data.objects['Cube'].game.properties['HIDE'].name='HIDE1'

To see all the properties members:
https://upbge.org/docs/latest/api/bpy.types.GameProperty.html#bpy.types.GameProperty

**Comment by rollalt** [comment]
Thanks. But this issue is not presented on the beta build on 2.9.

**Comment by lordloki** [comment]
In the beta build based on 2.9 that part was wrong and it was fixed. You can see it here:
![image](https://user-images.githubusercontent.com/1015605/146057484-3c091764-0d36-4981-b172-64b39e0cabfd.png)
But if you use that sentence what you really modify is the name of the object instead of the property name
![image](https://user-images.githubusercontent.com/1015605/146059520-aee8405c-cab4-4615-9ebd-52fe66234259.png)

Now you get an unfinished sentence but right until where you can see (just before the null).
Anyway, I will investigate it deeper to see if we can fix it in any form.

**Comment by lordloki** [comment]
I was investigating the issue and the way that Blender evolved I can't find a way to fix it. I will add a tag and I will close the issue.
If in the future I see a modification in this area by BF I will try to adapt the UPBGE code to fix the issue. Thanks for the feedback.
