### ISSUE TITLE
Some materials are totally pink in runtime (but them are working in standalone mode)

### ISSUE THREAD

**Issue by issimissimo** [UPBGE/upbge#1608]
Hello, I'm new to UPBGE (and to Blender as well).
I've did a very quick test with a scene with a couch, a table, a floor, etc.
Everything look pretty good in render viewport, as in embedded game mode, as in standalone game mode, while I'm in UPBGE.

![Cattura](https://user-images.githubusercontent.com/41523122/146603151-3f678a9e-d302-433d-a370-c94812280234.JPG)

BUT, when I export the game "file->export->Save as game runtime" as .exe (for PC) the table and the floor material are pink (like no shader is applied to them).

![Cattura01](https://user-images.githubusercontent.com/41523122/146603204-9925efd9-3d91-4958-910a-8b93a626637e.JPG)

1) These 2 objects have simple wood materials, that are not so different from the others materials in the scene.
For example this is a screenshot of the table material nodes

![Cattura02](https://user-images.githubusercontent.com/41523122/146603252-0e22c7c3-0e67-48b9-9101-c345b846c1d2.JPG)

2) These materials use external reference files for textures (not embedded in .blender file) but it's the same for all the others materials.
3) I've used default options during export.

Does someone can help me to understand what's going on?
Many thanks!

**Comment by issimissimo** [comment]
Ok, I've created a packed blender file with all the resources, and now it's working, 
BUT:
1 - the .exe file is increased from 300Mb to 1Gb (!!!)
2 - I don't understand why the .exe is increased so much (shouldn't all the external files be packed in the runtime version by default?)
3 - I can't still understand why I had to pack all the external files just for these 2 materials...

I think I'm missing something about how to deploy for the runtime version.
Any help on it would be much appreciated!

**Comment by lordloki** [comment]
Hi,
The .exe is increased so much because it is including your new resources (blend, images, etc). 
Depend on the size of your blends it will increase accordingly. Basicaly, the export .exe is composed of blenderplayer + your main blend and materials.
Really, you don't need to pack all your external files. You only need to pack the materials that you use.
Additionally, you can use relative links or load the files during the runtime to decrease the size of main .exe and to have a project more structured.
I close the issue because it is not a software bug but an usability issue. You can go at UPBGE's discord (https://discord.gg/vaFekZZr) to get more help relating UPBGE use.
Thanks for the feedback.
