### ISSUE TITLE
Not selecting the object when I click on it - Mac OS Monterey | UPBGE 0.30.0

### ISSUE THREAD

**Issue by mrcarromesa** [UPBGE/upbge#1627]
macOS Monterey
Version 12.1
Processor 1,8 GHz Dual-Core Intel Core I5
Memory 8 GB 1600 MHz DDR3
Graphics Intel HD Graphics 6000 1536 MB

UPBGE 0.30.0

The object doesn't select when I click directly on it, I need to click away a certain distance from the object to select it, as per video.

But in blender 3.0.0 it works correctly, the problem only occurs in UPBGE 0.30.0

https://user-images.githubusercontent.com/17169973/148648051-bf44fe3f-c716-4ba8-8ff7-8659e4623e8d.mp4

**Comment by BluePrintRandom** [comment]
can you try a blender nightly build?

we don't typically mess with this sort of stuff, so it may have crept into master as well

**Comment by mrcarromesa** [comment]
> can you try a blender nightly build?
> 
> we don't typically mess with this sort of stuff, so it may have crept into master as well

@BluePrintRandom, Thanks for answering!

So I downloaded the latest blender version from https://builder.blender.org/download/daily/

blender version 3.1.0 Alpha for MacOS, and everything is fine...

I saw that the upbge experimental downloads have the 0.31-alpha version, but only for linux and windows, do you know if macOS will be released soon too?

**Comment by lordloki** [comment]
Yeah, It is due to a bug in Xcode 13 and it was solved for blender 3.1 alpha. I will upload a MacOs build in a day with last master.

**Comment by lordloki** [comment]
I just uploaded a new build 0.31 Alpha for MacOS. Could you test it?

**Comment by mrcarromesa** [comment]
Yes now it's perfect!

Thank you very much, I will close this issue!

**Comment by chicortiz** [comment]
Hi guys!

Maybe is a good idea to have a Mac version inside the main download link ( [](https://upbge.org/#/download) )
Because the behaviour persists on 0.3.0.

Inside the service "Mega" someone can found a new version without this issue but I guess is a little less intuitive, maybe we can loose potential users because of that

( [](https://mega.nz/folder/t9EEFSaS#JPiOPSInCZyU-SW_-rhEOQ) )

I documented the issue here ( [](https://youtu.be/NjKBDo3ckzA) ) just for future reference (MacOS Mojave and Catalina, the same problem occurs but 0.3.5 Alpha solves this problem).

Greetings,

Ortiz
