### ISSUE TITLE
Logic nodes performance problems

### ISSUE THREAD

**Issue by Daniele-Barbieri** [UPBGE/upbge#1689]
hi everyone, i started to make a psx style game on upbge, the models have 800 tris, all textures are 256x256, no light or shadows, but the logic seem to be too heavy and also rasterizer and depsgraph, i thought that kind of game should work without any problem, so what 
are exactly rasteryzer and depsgraph and how to deal with them? how reduce performance? is  there a way to improve the logic with logic nodes only? i have an asus rog strix, i7, gtx 1060 6gb, 16 gb ram

https://user-images.githubusercontent.com/102927643/162072492-246874a3-8b78-4a32-bdbe-1bd59746b6b2.mp4

**Comment by ejamshidiasl** [comment]
performance in this video is good (really is the best)
if you want more FPS you must turn off "v-sync" in setting.

**Comment by Daniele-Barbieri** [comment]
Well, not really, after six or seven enemies on screen, fps goes down to 45, it's really slow, and things doesn't changes with vsync on or of
--
Inviato da Libero Mail per Android Giovedì, 07 Aprile 2022, 10:11AM +02:00 da Esmail Jamshidiasl  ***@***.*** :

**Comment by IzaZed** [comment]
Would you be willing to provide a file to see how you implemented the logic?

The Rasterizer is blender's "process" of projecting the scene onto the screen, so you might think of "Rasterizer" as something like "Graphics"
The DependencyGraph (DepsGraph) is a system to keep track of all the objects, their data and their relations to one another, so the less complicated parenting/constraint/modifier setup you have the better

**Comment by Daniele-Barbieri** [comment]
sure, but i don't know how woukd be understandable, some properties and trees are in english, others in italian, others both english and italian, anyway
[Fastus game.zip](https://github.com/UPBGE/upbge/files/8441676/Fastus.game.zip)

**Comment by Daniele-Barbieri** [comment]
i onestly hate logic bricks, i don't understand how to use them completely, and i would like not to restart the game from 0, so @IzaZed i ask you if is it possible, with that low poly style, to achieve a decent results without always struggling with performance with logic nodes only, i didn't recieve any answer on blender artist and from people that are upbge dayly users and didn't seem to have the same problems :')

**Comment by IzaZed** [comment]
I am sorry for the long delay, this completely slipped my mind
I checked out your file, and there's a huge amount of logic trees that seem to contradict each other or do the same/similar things on some occasions (I didn't understand a lot of it due to its complexity)
I think that a large part of this performance issue could be solved by boiling down the logic into optimized flows, it's also better to do as much as possible in one single tree, since each new tree adds to the overall workload for the engine

As for the feasibility of the project, I can't say. It depends on how much the character should be able to do, how big the map is, how many npcs there are etc.

**Comment by HolandonHdunto** [comment]
The problem may not just be in logic, upbge 0.3 materials are extremely heavy even with a good computer. If a project you want to start producing is stalling like this in the initial phase, you probably won't even be able to finish it.

  What you should be concerned about are the DRALL CALLS, the more materials and objects, the worse the performance, and if the game is made in upbge 0.3 the worsening intensifies.
   So it's better to use the upbge version 0.2.x.

**Comment by HolandonHdunto** [comment]
The problem may not just be in logic, upbge 0.3 materials are extremely heavy even with a good computer. If a project you want to start producing is stalling like this in the initial phase, you probably won't even be able to finish it.

  What you should be concerned about are the DRALL CALLS, the more materials and objects, the worse the performance, and if the game is made in upbge 0.3 the worsening intensifies.
   So it's better to use the upbge version 0.2.x.

**Comment by youle31** [comment]
I close this report as it is more logic nodes addon related (should be reported on logic nodes addon github), as IzaZed explained that some optimisations could be done on user side, as it's somewhat expected that some logic node setups are slow (because it is written in python), and as IzaZed will potentially try to do some optimizations later using cython.
