### ISSUE TITLE
LOD doesn't work properly

### ISSUE THREAD

**Issue by ThiagoMoraesGD** [UPBGE/upbge#1785]
LOD is intended for better performance, right? But in UPBGE it does the opposite. Hard FPS drop when LOD is active.

UPBGE 0.3.5

[lod_test.zip](https://github.com/UPBGE/upbge/files/10560836/lod_test.zip)

**Comment by youle31** [comment]
I've better rasterizer performances in your .blend with LOD enabled (0.5/1ms vs 10ms in lod disabled scene).

It Can only improve Raserizer performances in some cases, but it keeps more shapes in the draw cache even if these shapes won't be drawn (level of details which won't be drawn because of distance to camera). Anyway, for me it works as expected with your demo.
