### ISSUE TITLE
addObject on OverlayCollection spawns on other Collection

### ISSUE THREAD

**Issue by sevi78** [UPBGE/upbge#1793]
hi, 
i try to spawn objects on a OverlayCollection and experienced some weird behaviour. 
if an Object is spawned on an OverlayCollection, the Objects added on this collection are then spawned in the main Collection of the active Camera...

They are spawned right when the Camera on the Overlay is set as active Camera. But then they are invisible in the OverlayCollection---

i tried out actuators aswell, instantAddObject, addObject-Method. 
Theree might be a proper workaround to do, or nobody has ever spawned objects into OverlayCollections(?).
Or is it a bug? ...

https://github.com/sevi78/UPBGE-Tests

Btw: sidequestion: i dont know if i am this here is the right spot to discuss or post questions/Problems. 
I definitely dont want to waste your time, i highly appreciate your work here !
So should i continue post my experiences here, or someone recommend me another forum/repository to do so?
Thanks in advance

**Comment by youle31** [comment]
addObject/removeObject can't be used with overlay collections. To add something in overlay, you need a camera and a collection like in the following example:

[multi_overlay_test.zip](https://github.com/UPBGE/upbge/files/10750668/multi_overlay_test.zip)

Press numpad1 then numpad2

 (internally, everything is added where the active 
camera because old bge ignores collections and we choosed to add all objects replicas where is the active camera during runtime)

**Comment by youle31** [comment]
So, to add/remove something in overlay, it needs to use AddOverlayCollection/removeOverlayCollection (even if the collection has only one object). Overlay collections is not meant to be used with addObject/removeObject. I close this issue to clean the tracker as I think I answered.
