### ISSUE TITLE
[Request] Debug component properties

### ISSUE THREAD

**Issue by MoritzBrueckner** [UPBGE/upbge#445]
It would be helpful if there was a possibility to enable debugging of component properties like it is already possible with "normal" object properties.

I know that you have a lot of work and lately I opened a lot of new issues because of feature requests, so please see this as low priority and don't feel rushed :)

**Comment by panzergame** [comment]
@Momel15 : in the absolute this feature is feasible, but i'm asking me the interest because the component properties are the same than in the logic editor UI and your supposed to copy these value in the python component init function.

Do i miss something ?

**Comment by Momel15** [comment]
No, you don't miss something, it's my fault. I forgot that the values in the UI are only for initialisation. 

But for debug purposes it would be great to have a possibility to print the component properties directly to the screen instead of print() like "normal" properties. There could be the possibility to allow debug display all python variables (_bge.render.addDebugProperty(instance/class?, prop)_ or so), but as most scripts (unless they are modules) use variables only for one frame, this would of course only make sense for modules.

e.g.:

```python
import bge
from collections import OrderedDict

class Test(bge.types.KX_PythonComponent):
    args = OrderedDict([
        ("Test", 0)
    ])

    def start(self, args):
        self.test = args['Test']

        # "registers" the variable self.test as a debug property
        bge.render.addDebugProperty(self, self.test) # <- Every frame this variable gets read and displayed
        # Problem: I think blender needs to know from where the variable comes,
        # as there are no pointers in python (or am i wrong? I'm not very good at python)
        # To solve this, there could be another parameter to pass the instance 
        # of the class that contains the variable.

    def update(self):
        pass
```

This is clearly not the best solution (if there _is_ a solution at all)

What do you think about that?

**Comment by panzergame** [comment]
What about a function in the component returning the text to debug ?

```
class Component(bge.types.KX_PythonComponent):
       def debug(self):
            return ("Component", "prop :", self.prop)
```

Output:
```
Component
prop : 5
```

**Comment by Momel15** [comment]
This would be great!

But how to handle more than one variable? Like this?
```
def debug(self):
    return ("Component", "prop :" + str(self.prop), "prop1" :" + str(self.prop1))
```

And then the output would be like
```
Component
prop : 5
prop1 : 6
```
?

**Comment by panzergame** [comment]
That is, one item per line.

**Comment by Momel15** [comment]
Ok great

**Comment by lordloki** [comment]
Closing as new tracker rules but open and feature for later tags added.
