### ISSUE TITLE
Optimize mesh polygon sorting.

### ISSUE THREAD

**Issue by panzergame** [UPBGE/upbge#727]
Here a list of ideas to optimize the sorting of the polygons:
- use a copy of the mesh indices per mesh slots and update all of them in parallel ;
- use a unique IBO per mesh slot and bind it during rendering.
- use a BVH of KD tree

**Comment by BluePrintRandom** [comment]
if the scene data was built as bvhtree for forward+ lamp discard, the same
data could return elements in clip of camera sorted I think

On Jun 30, 2018 11:52 AM, "panzergame" <notifications@github.com> wrote:

Here a list of ideas to optimize the sorting of the polygons:

   - use a copy of the mesh indices per mesh slots and update all of them
   in parallel ;
   - use a unique IBO per mesh slot and bind it during rendering.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/UPBGE/blender/issues/727>, or mute the thread

**Comment by panzergame** [comment]
Reference: https://www.seas.upenn.edu/~pcozzi/OpenGLInsights/OpenGLInsights-AsynchronousBufferTransfers.pdf

**Comment by lordloki** [comment]
I close this as it is under eevee render responsability now.
