### ISSUE TITLE
Mix animation Via python

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/upbge#759]
say I want to remake a game state from game data,

right now the animation system does not really support this. (creating a pose and applying it)

I was thinking, we need a api that can mix and manipulate animations

animation3 = animationLerp( [anim1, frame], [anim2,frame], rate)

so animation 3 would be the result of animation 1's pose frame lerped to animation 2's pose frame

then we need a way to override and set the animation state

```
#directly set the pose using py
armature.animation = animation3

#stop the armature from playing an animation
armature.playing = False

#manipulate the currently playing action list as unique objects
armature.actions = [ [anim_data1],[anim_data2] ]

```

**Comment by UnidayStudio** [comment]
But **we already can do this** by running each animation in a different layer and controlling the **layer weight**. I'm using this kind of interpolation in my Character Controller template. (I'll commit the code doing this soon).

But I've to say that if you want to change the layer weight in realtime, during the action run cycle, (by default,  it will only be changed when the animation restarts) you've to do a small workaround, calling stopAction (layer) before aplying the new value. Improve this will be interesting.

**Comment by lordloki** [comment]
Yeah, the solution pointed by uniday seems me the right way to achieve the interpolation. Thanks for the feedback. I close this

**Comment by UnidayStudio** [comment]
Alright. 

Sorry to "revive" this issue, but I'm here with the solution (possibly) + code snippets. 😄 

# Layer Weight!

People "PMed" me today asking me about this feature request, if I had any progress in it and I remembered something: It turns out that I had actually implemented this layer weight feature, but it was local on my machine and I forgot to commit back then. 

I no longer have the changes, but I sort of remember what I had to do in order to make it work (it was not that complicated). Unfortunatelly I've been very busy lately doing some work and personal life stuff, so I was not able to get it compiling and test things out. But I've opened the sources here thought github (browser) and tried to mimic what I did back then. 

If someone wants to try it out, I'll leave everything here in this comment (so feel free to implement it yourself). Or... you can ping me here in about two weeks and I may be able to give it a test run (hopefully I'll have some time).

## So here is how I did it...

In a nutshell, all we have to do is to create the appropriate APIs, in the GameObject, to change the `m_layer_weight` variable of the `BL_Action` being executed on a given layer, using a method like `object.setActionLayerWeight(1, 0.5). May be a good idea to follow this same principle in the code to also make a getter (to get the current weight: `w = object.getActionLayerWeight(1)`). 

It is really not hard, because there is no extra code required other than just exposing this variable to the API.

Here is the simplest implementation possible. I'll discuss some points afterwards, but here it is (this should do the trick just fine):

In `KX_GameObject.[h|cpp]`:
```cpp
void KX_GameObject::SetActionLayerWeight(short layer, float layer_weight){
	GetActionManager()->SetActionLayerWeight(layer, layer_weight);
}
```

In `BL_ActionManager.[h|cpp]`:
```cpp
void BL_ActionManager::SetActionLayerWeight(short layer, float layer_weight){
	BL_Action *action = GetAction(layer);
	
	if (action){
		action->SetLayerWeight(layer_weight);
	}
}
```

And finally, in `BL_Action.[h|cpp]`:
```cpp
void BL_Action::SetLayerWeight(float layer_weight){
	m_layer_weight = layer_weight;
}
```

Unfortunatelly, I don't remember how to expose that to the Python API anymore. But it probably is as simple as just adding the method as an `EXP_PYMETHOD_DOC` (based on how other GameObject's method are exposed, such as `playAction`). Check this code snippet as a reference:
https://github.com/UPBGE/upbge/blob/upbge0.2.5/source/gameengine/Ketsji/KX_GameObject.h#L889

# How to test it...

I also don't have the test blend file anymore, but it should be very straight forward:

- Open UPBGE 0.2.5 and add an armature with a mesh (so we can see it working).
- Create two distinct animations (can be an idle and an walk anim, or something very simple, but with different poses so we can see it changing weights).
- Then program a logic that:
	- Play both actions, at layer 0 and 1, each.
	- Change the layer 1's weight as it is playing the animation

Here is a simple python component example that does the logic part for you:
```py
import bge
import time
import math

class Component(bge.types.KX_PythonComponent):
    args = {}

    def start(self, args):
        pass

    def update(self):
		# Playing the actions in both layers (0 and 1):
		self.object.playAction("Anim1", 0, 100, layer=0)
		self.object.playAction("Anim2", 0, 100, layer=1)
		
		# Now I'll change the layer 1 weight using a timer...
        weight = (math.sin(time.time()) + 1.0) / 2.0
        print("The weight will be set to %.4f" % weight)
		
		# That's the new function...
		self.object.setActionLayerWeight(1, weight)
		
		# And we could also have this one:
		#newLayerOneWeight = self.object.getActionLayerWeight(1)
```

You should be able to see it cycling between the two animations. :)

# Now some important notes...
__(for the software engineers reading this)__

Notice that adding this API requires a "shotgun surgery" in the code. Unfortunatelly, that's not uncommon in Blender and BGE's code. It will work fine and as I said, it's the simplest solution for this feature request. But it would be a better idea to try to reduce how deep the calls needs to go, because it will also make it easier to add new and better Action APIs to the python end in the future.

**A good example of this** would be to also change the animation's `speed` variable during its execution. Without this refactor, the procedure would be the exact same as I listed before for the layer_weight, but the speed field (and many others) could be easily set if we had Python access to the `BL_Action` being executed.

**How to do that?**

After some inspection in the `KX_GameObject`, I noticed that pretty much all the animation related methods are basically just getting the Action Manager (`BL_ActionManager`) and calling the same function from it (feature envy). May be a good idea to literally just expose the `BL_ActionManager` class to the Python end and then the `KX_GameObject::GetActionManager` method. It is a private method, but I don't see a reason for it. This refactor will not break backwards API compatibility and will already make our life a bit simpler...

To complete, in the `BL_ActionManager`, we could also expose the `BL_Action* BL_ActionManager::GetAction(short layer)` method to the API (and, of course, the `BL_Action` class as well). 

The only concern here is that the BL_Action **may be deleted** at some point (from what I was able to inspect, but again, I did not had much time to confirm it), causing mem violation problems if we don't handle it properly. 

Unfortunatelly, to this "better enhancement", I don't have enought BGE's source code knowledge to figure out how to expose entire classes to the Python API. :P
