### ISSUE TITLE
Add an option to quit game after a python error.

### ISSUE THREAD

**Issue by UnidayStudio** [UPBGE/upbge#825]
Right now, if you have an error in your script, the game engine will still running and printing the error in the console every frame. This may be good if you're testing, but in most cases, is very bad to debug and see what is happening. Example: You wrote a name of a function wrong in the start function, so the start function didn't finish running and adding properties on the object (for example). Python outputs the error in the console. No problem. But right after this, the frames starts running, the update function will not work because the properties where not initialized and python will print thousands of other errors every frame, making impossible to scroll up to see the first error.

In big projects, which the objects have some connectiong, this may be a nightmare. The solution: Add a checkbox to quit game when an error appears.

**Comment by Jesusemora** [comment]
i dont see the point to this, if there is a bug you just follow it from the point of error up the code. you can never predict when a bug will happen, sometimes is a typo, but sometimes the entire thing is wrong, your aproach is wrong, there is a line missing, you are using python wrong, something doesn't work in a certain way anymore, you forgot to define a variable or property, you forgot to connect a brick, or one that happened to me many times; you wrote a function and forgot to call it in the script, so it's never going to do anything.
the advantage of python in game is that the game will continue to work and you can see the bug and why it happens INGAME. there is a procedure to be followed to diagnose a problem, it is the same when repairing a computer, in medicine, and coding is no exception. activating this option will only interfere with the proccess of diagnosis so i don't think it will be used at all.
the problem you present should be fixed by disabling everything that's sending an error until it shows nothing, then you enable them one by one to find the one that's creating the problem.
another way is to write from each script on to a dictionary after it has run succesfully, then save this to a text file. that way you know exactly wich scripts worked and wich failed outside of the console.

```
def logFile(wichscript):
     debug = bge.logic.globalDict['debug']
     debug.append(wichscript+"_success")
     bge.logic.globalDict['debug'] = debug
```

then pressing a key runs a script wich saves the dictionary using `f.Open()`

if you have a problem with multiple errors in console, why don't you ask for an option to change the number of lines in the console instead? an option in settings or somewhere else with a default number of lines for the console that can then be increased?

**Comment by UnidayStudio** [comment]
I don't want to have a block of 5000 lines with the same error. I understand and take your point in consideration. That's why I suggested a checkbox (true of false) to quit the game. If you don't want, just disable it.

**Comment by marechal-p** [comment]
You can use Python `excepthook` that gets triggered on each exception.

```py
from bge import logic
import sys

hook = sys.excepthook

def custom_hook(type, value, traceback):
    hook(type, value, traceback)
    logic.endGame()
    
sys.excepthook = custom_hook

def setup(controller):
    owner = controller.owner
    
    @owner.collisionCallbacks.append
    def on_collision(object):
        raise Exception(f'hit something, oops: "{object}"')
```

[UPBGE_QuitOnError.zip](https://github.com/UPBGE/blender/files/2453558/UPBGE_QuitOnError.zip)

**Comment by panzergame** [comment]
@marechal-p It's what i'm trying to implement in engine directly, If you have motivation and time you can give a try.

**Comment by lordloki** [comment]
I pass this for 0.3
