### ISSUE TITLE
UPBGE's console is unable to show non-ASCII characters

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/upbge#868]
The example files are provided below.

- The `script.py` can be executed both through an standalone Python or UPBGE's Python controller (blend file provided).
- Note the non-ASCII characters not being properly represented in console, UPBGE's Python is not being able to represent them as unicode.
- The text file `1.txt` is encoded as UTF-8.
- Both Python versions (UPBGE and standalone) are 3.7.

![image](https://user-images.githubusercontent.com/19820741/46481405-b4c58e80-c7c9-11e8-99da-d4d740206005.png)

![image](https://user-images.githubusercontent.com/19820741/46481451-d0309980-c7c9-11e8-8be0-3859679409a9.png)

[ex_open_utf8.zip](https://github.com/UPBGE/blender/files/2446790/ex_open_utf8.zip)

**Comment by panzergame** [comment]
@lordloki @youle31 : Can you reproduce this issue ? On linux the UTF-8 support is correct but the system is certainly helping.

**Comment by lordloki** [comment]
lastest master I can see the issue yet
![image](https://user-images.githubusercontent.com/1015605/46576525-0a698900-c9cc-11e8-8743-61b40522174d.png)

**Comment by lordloki** [comment]
After investigate a bit, this is an issue enough extended in Windows. The issue comes from the default console doesn't have UTF-8 support. 

Then the solution will be to execute 'chcp 65001' before to launch blender.exe. This can be automated with a .bat or similar script.

I close the issue. If the solution doesn't fix the issue for you, please feel free to open issue again. Thanks for reporting.
