### ISSUE TITLE
UPBGEv0.2.4b2.79Linux64 not opening on Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by chicortiz** [UPBGE/upbge#943]
Hello UPBGE Developers. 

I downloaded the Linux version for "Debian-based OS"  (UPBGEv0.2.4b2.79Linux64) and the application is not opening by clicking. After I click the Blender binary There is a pop up window that reads: "There is no application installed for "Shared Library" files. Do you want to search for an application to open this file?". However If I start blender via terminal It loads :)

**Comment by lordloki** [comment]
Hi,
This is an known issue of nautilus browser.
https://askubuntu.com/questions/861696/ubuntu-doesnt-think-that-file-is-executable

**Comment by lordloki** [comment]
@panzergame from stackoverflow:

I have fixed this behavior by adding the following line on my project's .pro file in QT:

QMAKE_LFLAGS += -no-pie
The behavior is occurring because newer ubuntu distros set GCC default link flag -pie, which marks e_type as ET_DYN on the binary file. Consequently, the Operating System recognizes as Shared Library.

To work around it, it may be necessary to add -no-pie on compiler option.

https://stackoverflow.com/questions/45329372/ubuntu-recognizes-executable-as-shared-library-and-wont-run-it-by-clicking?answertab=active#tab-top

Then adding -no-pie to the linker solve this.

**Comment by lordloki** [comment]
Now we do the builds from CentOS and therefore we avoid this issue.
Thanks for reporting. Closing the report
