### ISSUE TITLE
zsh: segmentation fault (core dumped)  ./blender

### ISSUE THREAD

**Issue by ethicalfive** [UPBGE/upbge#960]
Reporting for a friend. He has not been able to get upbge to run.

GPU, OS - Original Titan (libGLX_nvidia.so.415.22) Arch Linux
Output of the bug: https://pastebin.com/0sJLYxbg -- Original error + cat /tmp/blender.crash.txt
Output of valgrind: https://pastebin.com/HvVKYZed

Detail of the UPBGE used: compiled current master (as of this report) without compile errors. Vanilla 2.79 runs, 2.8 also segfaults. Also segfaults with the latest stable linux64 binary download.

**Comment by youle31** [comment]
Notes:

- This is a crash at Blender opening then there are chances that the bug is related to BF code
- lordloki suggested to try to compile without open color io (OCIO) as we had some issues with the commit 0.2.4 is based on.
- Last 2.79 build from buildbot seems to not crash

- I think waiting for the next merge (and if this still doesn't work compiling without OCIO), maybe the better would be to continue to use 0.2.3 until we do the next merge with BF sources.

**Comment by ethicalfive** [comment]
So he tried recompiling without opencolorio, which didn't change anything, so he disabled everything and narrowed it down to ffmpeg. Although while the blender binary runs, the blenderplayer binary still segfaults.

He also says that valgrind is complaining about audio even if he runs with "-g noaudio" but he's not sure if the segfault has anything to do with that particular problem. this is his valgrind output https://pastebin.com/z24T7hWb

**Comment by lordloki** [comment]
Maybe it is related to this commit https://github.com/UPBGE/blender/commit/6e8870b4854757998ead2f754eacab45144fdf91

And this crash https://blender.stackexchange.com/questions/77857/error-al-lib-updatedeviceparams-failed-to-set-44100hz-got-48000hz-instead-wh
But with 48000 instead of 44100.

Could you revert the commit (pass 48000 to 44100 in source/gameengine/GamePlayer/GPG_ghost.cpp) and compile again?. If blenderplayer works this way i will add a new -g audio_rate option available.

To solve the blender binary follow the solution exposed in the link above.

**Comment by lordloki** [comment]
Closing the issue
