### ISSUE TITLE
Is it possible to bring the image as text back?

### ISSUE THREAD

**Issue by MarllonxD3** [UPBGE/upbge#979]
I know the image as text option was taken from the upbge, but does anyone know a way to do this? Do not you have an addon for that?
I have already done several tests with the blender text, but I still prefer the bitmap.
I really like this option because I can modify the look in several ways.

**Comment by lordloki** [comment]
@panzergame, @youle31 we need to discuss this again.
This feature seems useful as it is asked frequently.

Former issue #469 with more info
Pull request from @youle31 : https://github.com/UPBGE/blender/pull/470

**Comment by youle31** [comment]
yeah, I think this would be cool to restore it as it was used by some known game makers and as I don't know if there will be a transition to 2.8 finally. I heard the request several times too, and the code must still be there in last BF 2.79 sources. I don't know if there is a technical inconvenient to restore it.

**Comment by MarllonxD3** [comment]
Thank you guys!
is it possible to make it manually, using python?
I have a project here and I wish I could use this

**Comment by BluePrintRandom** [comment]
You can use a uv texture, and save the uv of each letter in a dictionary
along with the letter width,  and spawn copies of a plane and set the uv.

Uv, spacing = letterDict[ letter]

**Comment by Jesusemora** [comment]
i've used sprites to create scores, and have been testing it to use in long texts. speed is really good, there is almost no delay. i've tested it with around 600 characters and fps remains at 60.

basically, i created objects for every character, and named them like "aa" "ba" "ca" "Aa" "Ba" etc. a script looks at the objects with a specific property from a list of names, and uses `replaceMesh(currentCharacter+"a")` to change the mesh of the objects. (every object represents a "slot" that will be occupied by a character). if there's a space, it replaces the object with one that's transparent. (you could make it `visible=False`, but you would have to add a line of code that makes slots `visible=True` when there's no space, so i don't know if there's really an advantage)
good thing is i can put only the characters i want, if i'm making a score, i can use only numbers.

the current bge text objects are awfully bad, they require special properties to function, they are limited to a single color, they do not support bold or itallic, and they come in a resolution that's too small for use in games. i've had to increase size using textObject.resolution and put it at at least 10 or 12, and it causes a delay, some resolutions causes crashes, and there's a bug that causes text to disappear when opening a different blend, wich can only be fixed by closing and reopening blender.
the only advantage is that it allows newbies and people who are in a hurry to change the font for a different one and not have to create an image in an image editor like gimp.

a new text system should have to fix all these issues, meanwhile, my solution seems to work, but i need to do some more testing.

**Comment by joelgomes1994** [comment]
@BluePrintRandom 
> You can use a uv texture, and save the uv of each letter in a dictionary along with the letter width, and spawn copies of a plane and set the uv.
> Uv, spacing = letterDict[ letter]

Although this is the best idea to make a reusable text asset, you currently can't: as the UV, mesh, material and texture are shared between objects, once you change any of them, it changes everything else. In a exemple of several characters added through a iteration, each character added will be changed to its own UV coordinates, but the latest character will make the previous change as well. Here's a example using `uvOffset` that should have been worked, but it didn't because of the shared nature of datablocks. I don't know about `transformUV` because it's not working (probably it's worth opening an issue to it).
[ex_dyn_text_uvOffset.zip](https://github.com/UPBGE/blender/files/2716318/ex_dyn_text_uvOffset.zip)

@Jesusemora
> basically, i created objects for every character, and named them like "aa" "ba" "ca" "Aa" "Ba" etc. a script looks at the objects with a specific property from a list of names, and uses `replaceMesh(currentCharacter+"a")` to change the mesh of the objects. (every object represents a "slot" that will be occupied by a character). if there's a space, it replaces the object with one that's transparent. (you could make it `visible=False`, but you would have to add a line of code that makes slots `visible=True` when there's no space, so i don't know if there's really an advantage)
> good thing is i can put only the characters i want, if i'm making a score, i can use only numbers.

In the example below I did the same as you, but instead of one object for each character I did one face for each character, and I used shape keys animation to change the current character. It avoids lots of objects in the scene and makes it more 'portable'. The only drawback is all the faces present in scene (even being culled). Think of a 2000 characters text, and each character with 100 faces, surely it would have a performance issue. A better option was by using the `uvOffset` method, if it worked.
[ex_dyn_text_shapekeys.zip](https://github.com/UPBGE/blender/files/2716332/ex_dyn_text_shapekeys.zip)

> they require special properties to function

`obj.text` or `obj['Text']`?



> they are limited to a single color

![image](https://user-images.githubusercontent.com/19820741/50537933-1047b400-0b4e-11e9-88cb-3620c772b97b.png)

Then, you can change it through `obj.color`.

> and there's a bug that causes text to disappear when opening a different blend, wich can only be fixed by closing and reopening blender

I see this bug frequently, it's pretty annoying.

> the only advantage is that it allows newbies and people who are in a hurry to change the font for a different one and not have to create an image in an image editor like gimp

Unfortunately you can't do that in-game, which could suppress a lot of the mentioned limitations. With the bitmap text you could at least change the texture using `bge.texture.Texture` and `bge.texture.ImageFFmpeg`.

I was trying to make a custom text asset (as you can see in the two examples provided above), and the best option (using `uvOffset`), which would allow the user to set the mapping of the characters easily through a text definition file, can't be used because of the shared nature of datablocks between objects. 

Usually, when something can be done in some way, I would not insist for a 'new feature', but as there's no easy way to make texture based dynamic texts anymore, the return of bitmap text is surely a need.

**Comment by Jesusemora** [comment]
> In the example below I did the same as you, but instead of one object for each character I did one face for each character, and I used shape keys animation to change the current character. It avoids lots of objects in the scene and makes it more 'portable'. The only drawback is all the faces present in scene (even being culled). Think of a 2000 characters text, and each character with 100 faces, surely it would have a performance issue. A better option was by using the uvOffset method, if it worked.

using animations is an extra layer of complexity that is not needed. and as you said yourself, it's expensive.

my method is better because the replaceMesh is used once to load an entire text, there could be a slowdown of a few microseconds, and it will run at 60 fps after that. with you method it will always have to calculate animations for every object every frame. i can also put all the characters into a single batch if in a text, since they are static if in a different scene.
the number of characters goes from 10 for just numbers, 40 for words, and around 60/70 if using more ascii characters like "?", "'", "!", or even "ñ".

> obj.text or obj['Text']?

what bothers me is having two sepparate sets of properties in the object properties tab. i never know wich to use but it always works. of course i use obj.text in python, but there's too many options for something so simple.

> Then, you can change it through obj.color.

i mean that the entire text is a single color. with my method i used obj.color and then i'm able to change the color of individual characters. i made a multicolored text.

i can also texture the text object and get a more cartoony and colored text than just a plain color. i can also use nodes to ANIMATE the colors, apply a texture on it, lots of things.

> Unfortunately you can't do that in-game, which could suppress a lot of the mentioned limitations. With the bitmap text you could at least change the texture using bge.texture.Texture and bge.texture.ImageFFmpeg.

i don't mean chaging text font during game. i meant choosing a font different from the default for you particular game, customize the font.

here is sample code of what i did:
````
def create_sprites():
    fou = 0
    for abc in range(12):
        for adc in range(75): #75
            ob1 = scene.addObject("text_sprite", obj, 0)
            ob1.worldPosition = [-1.63+(0.04*adc), -0.61-(0.08*abc), 0.0]#-0.81-(0.08*abc), 0.0]
            ob1.name = "letter"+str(fou)#adc*abc)
            ob1.color = [1.0, 1.0, 1.0, 1.0]
            ob1.replaceMesh("blank_space")
            fou = fou + 1

t_format = {'0': [0.0, 0.0, 0.0, 1.0], #black
'1': [1.0, 1.0, 1.0, 1.0], #white
'2': [1.0, 0.0, 0.0, 1.0], #red
'3': [0.0, 1.0, 0.0, 1.0], #green
'4': [0.0, 0.0, 1.0, 1.0], #blue
'5': [1.0, 1.0, 0.0, 1.0], #yellow
'6': [0.0, 1.0, 1.0, 1.0], #cyan
'7': [1.0, 0.0, 1.0, 1.0], #magenta
'8': [1.0, 0.5, 0.0, 1.0], #orange
'9': [0.5, 0.5, 0.5, 1.0], #grey
'a': [0.5, 1.0, 0.5, 1.0], #bright green
'b': [1.0, 0.5, 0.5, 1.0], #bright red
'c': [0.5, 0.5, 1.0, 1.0], #bright blue
'd': [1.0, 1.0, 0.5, 1.0], #bright yellow
'e': [0.5, 1.0, 1.0, 1.0], #bright cyan
'f': [1.0, 0.5, 1.0, 1.0], #bright magenta
'g': [1.0, 0.75, 0.5, 1.0], #bright orange
'h': [1.0, 0.5, 0.75]} #bright purple
````
````
endofline = (75, 151, 226, 301, 376, 451, 526, 601, 676, 751, 826, 901)

def is_a_button(set_on, obe):
    if set_on == 1:
        obe["Button"] = 1

def write_text(text):
    caracter = 0
    encoded = [1.0, 1.0, 1.0, 1.0]
    encode_active = 0
    set_button = 0
    #74 149 224 299 374 449 524
    #red yellow white cyan brown-orange-red purple grey grey-cyan
    for hij in text:
        letter = objList.get("letter"+str(caracter))
        is_a_button(set_button, letter)
        #if hij == "\n":#            encode_active = 1
        if encode_active == 1:
            encoded = t_format[hij]
            encode_active = 0
        elif hij == "$":
            #color
            encode_active = 1
        elif hij == " ":
            letter.replaceMesh("blank_space")
            caracter = caracter + 1
        elif hij == "\n":
            for eee in endofline:
                if caracter < eee:
                    caracter = eee
                    break
        elif hij == "@":
            pass
        elif hij == "¬":
            caracter = caracter + 1
        elif hij == "|":
            pass
        elif encode_active == 0:
            letter.replaceMesh(hij+"a")
            letter.color = encoded
            caracter = caracter + 1
````
````
create_sprites()
write_text("$ctext $1TEXT \n¬text text text $0text text $4text abcdefghijklmnopqrstuvwxyz")
````

**Comment by BluePrintRandom** [comment]
About the uv, we have mesh.copy() making it so we don't need to muck around
with libnew

On Dec 29, 2018 10:13 AM, "Jesusemora" <notifications@github.com> wrote:

In the example below I did the same as you, but instead of one object for
each character I did one face for each character, and I used shape keys
animation to change the current character. It avoids lots of objects in the
scene and makes it more 'portable'. The only drawback is all the faces
present in scene (even being culled). Think of a 2000 characters text, and
each character with 100 faces, surely it would have a performance issue. A
better option was by using the uvOffset method, if it worked.

using animations is an extra layer of complexity that is not needed. and as
you said yourself, it's expensive.

my method is better because the replaceMesh is used once to load an entire
text, there could be a slowdown of a few microseconds, and it will run at
60 fps after that. with you method it will always have to calculate
animations for every object every frame. i can also put all the characters
into a single batch if in a text, since they are static if in a different
scene.
the number of characters goes from 10 for just numbers, 40 for words, and
around 60/70 if using more ascii characters like "?", "'", "!", or even "ñ".

obj.text or obj['Text']?

what bothers me is having two sepparate sets of properties in the object
properties tab. i never know wich to use but it always works. of course i
use obj.text in python, but there's too many options for something so
simple.

Then, you can change it through obj.color.

i mean that the entire text is a single color. with my method i used
obj.color and then i'm able to change the color of individual characters. i
made a multicolored text.

i can also texture the text object and get a more cartoony and colored text
than just a plain color. i can also use nodes to ANIMATE the colors, apply
a texture on it, lots of things.

Unfortunately you can't do that in-game, which could suppress a lot of the
mentioned limitations. With the bitmap text you could at least change the
texture using bge.texture.Texture and bge.texture.ImageFFmpeg.

i don't mean chaging text font during game. i meant choosing a font
different from the default for you particular game, customize the font.

here is sample code of what i did:

def create_sprites():

    fou = 0

    for abc in range(12):

        for adc in range(75): #75

            ob1 = scene.addObject("text_sprite", obj, 0)

            ob1.worldPosition = [-1.63+(0.04*adc), -0.61-(0.08*abc),
0.0]#-0.81-(0.08*abc), 0.0]

            ob1.name = "letter"+str(fou)#adc*abc)

            ob1.color = [1.0, 1.0, 1.0, 1.0]

            ob1.replaceMesh("blank_space")

            fou = fou + 1



t_format = {'0': [0.0, 0.0, 0.0, 1.0], #black

'1': [1.0, 1.0, 1.0, 1.0], #white

'2': [1.0, 0.0, 0.0, 1.0], #red

'3': [0.0, 1.0, 0.0, 1.0], #green

'4': [0.0, 0.0, 1.0, 1.0], #blue

'5': [1.0, 1.0, 0.0, 1.0], #yellow

'6': [0.0, 1.0, 1.0, 1.0], #cyan

'7': [1.0, 0.0, 1.0, 1.0], #magenta

'8': [1.0, 0.5, 0.0, 1.0], #orange

'9': [0.5, 0.5, 0.5, 1.0], #grey

'a': [0.5, 1.0, 0.5, 1.0], #bright green

'b': [1.0, 0.5, 0.5, 1.0], #bright red

'c': [0.5, 0.5, 1.0, 1.0], #bright blue

'd': [1.0, 1.0, 0.5, 1.0], #bright yellow

'e': [0.5, 1.0, 1.0, 1.0], #bright cyan

'f': [1.0, 0.5, 1.0, 1.0], #bright magenta

'g': [1.0, 0.75, 0.5, 1.0], #bright orange

'h': [1.0, 0.5, 0.75]} #bright purple


endofline = (75, 151, 226, 301, 376, 451, 526, 601, 676, 751, 826, 901)



def is_a_button(set_on, obe):

    if set_on == 1:

        obe["Button"] = 1



def write_text(text):

    caracter = 0

    encoded = [1.0, 1.0, 1.0, 1.0]

    encode_active = 0

    set_button = 0

    #74 149 224 299 374 449 524

    #red yellow white cyan brown-orange-red purple grey grey-cyan

    for hij in text:

        letter = objList.get("letter"+str(caracter))

        is_a_button(set_button, letter)

        #if hij == "\n":#            encode_active = 1

        if encode_active == 1:

            encoded = t_format[hij]

            encode_active = 0

        elif hij == "$":

            #color

            encode_active = 1

        elif hij == " ":

            letter.replaceMesh("blank_space")

            caracter = caracter + 1

        elif hij == "\n":

            for eee in endofline:

                if caracter < eee:

                    caracter = eee

                    break

        elif hij == "@":

            pass

        elif hij == "¬":

            caracter = caracter + 1

        elif hij == "|":

            pass

        elif encode_active == 0:

            letter.replaceMesh(hij+"a")

            letter.color = encoded

            caracter = caracter + 1


create_sprites()

write_text("$ctext $1TEXT \n¬text text text $0text text $4text
abcdefghijklmnopqrstuvwxyz")


—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/UPBGE/blender/issues/979#issuecomment-450510328>, or mute
the thread

**Comment by joelgomes1994** [comment]
> About the uv, we have mesh.copy() making it so we don't need to muck around with libnew

It doesn't work, I tried it in the example sent before.

[ex_transformUV.zip](https://github.com/UPBGE/blender/files/2717290/ex_transformUV.zip)

**Comment by BluePrintRandom** [comment]
you are moving the texture over bud, not moving the vertex UV

vertex are owned by the mesh - textures are a separate thing.

check vertex.UV and vertex.UVS
https://pythonapi.upbge.org/bge.types.KX_VertexProxy.html?highlight=vertexproxy%20uv#KX_VertexProxy.UV

**Comment by joelgomes1994** [comment]
Well, don't blame me for not having discovered that `uvOffset` doesn't actually move UVs Haha
Thanks, it works now. ;)

[ex_dyn_text_VertexProxyUV.zip](https://github.com/UPBGE/blender/files/2718008/ex_dyn_text_VertexProxyUV.zip)

> you are moving the texture over bud, not moving the vertex UV vertex are owned by the mesh - textures are a separate thing. check vertex.UV and vertex.UVS https://pythonapi.upbge.org/bge.types.KX_VertexProxy.html?highlight=vertexproxy%20uv#KX_VertexProxy.UV

**Comment by BluePrintRandom** [comment]
@lordloki could we use GE_Mesh_Builder and this system (set uv of planes) to get bitmap text working again?

(so a bitmap text is a unique mesh that each additional letter / character is 2 triangles?)

**Comment by lordloki** [comment]
I checked to recover it for 0.2.5 but the code changes so much and it would take so much time to recover it. Then I close this but I add a feature request for later and open to check again for 0.3
