### ISSUE TITLE
Physics Does Not Update in Scene Transition

### ISSUE THREAD

**Issue by EndSSgamesStudio** [UPBGE/upbge#994]
Physics Bullet Not updated during Cena's transition

The Physiques Are Individual for each scene, plus if you have a scene with modified physics, and make the transition from one scene to another, the modified physics continues, instead of updating to the paramenters of the current scene.

Note: in the file, press the right button to change scene.

here: http://pasteall.org/blend/index.php?id=51081

This was my attempt to force the physics to update: http://pasteall.org/blend/index.php?id=51082

**Comment by BluePrintRandom** [comment]
Are you trying to set something global using a scene parameter? 

please explain what is happening, and what you feel should be happening,

**Comment by EndSSgamesStudio** [comment]
Hi. @BluePrintRandom 
I'm not trying to define something global, it's the reverse of this.
every scene has its own independent physics

![screenshot_20190126055013](https://user-images.githubusercontent.com/35436445/51784344-52085200-212e-11e9-82c0-3e3b8a2b4962.png)

but when changing scene,this is not respected...

physics continues from the previous scene

**Comment by UglinessInTheUI** [comment]
You can check in script the scene name and set the time scale based on scene name. Try something like:

from bge import logic
scene = logic.getCurrentScene()

if scene.name == 'Scene':
    logic.setTimeScale(0.05)

if scene.name == 'Scene2':
    logic.setTimeScale(10)

[Test2.zip](https://github.com/UPBGE/blender/files/2874406/Test2.zip)

**Comment by youle31** [comment]
With scene actuator the physics remain the same than the startscene. There is only a change if you use Game Actuator (Load Blend). This is not really a bug, but more a design decision (physics time is set in LA_Launcher:

I think this is that:

m_ketsjiEngine->SetTicRate(gm.ticrate);
m_ketsjiEngine->SetMaxLogicFrame(gm.maxlogicstep);
m_ketsjiEngine->SetMaxPhysicsFrame(gm.maxphystep);
m_ketsjiEngine->SetTimeScale(gm.timeScale);

and LA_Launcher pipeline is not executed if you only change the scene with scene actuator.

It is true that physics settings are in "scene tab" and you might expect that the physics time is per scene but in the same time the current behaviour to keep the physics settings from the startscene (the first scene launched) can make sense too (also from coding point of view).

As we can either use python API (setTimeScale), either use game actuator load blend instead of scene actuator... I close this report because this is a code design decision, changing this behaviour could cause backward compatibility issues and maybe other issues that we can't see for now...
